stella_ahrs_node:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baud_rate: 115200
    publish_tf: false
    frame_id: "imu_link"
    parent_frame_id: "base_link"
    linear_acceleration_stddev: 0.02
    angular_velocity_stddev: 0.01
    magnetic_field_stddev: 0.00000327486
    orientation_stddev: 0.00125
